spring:
  datasource:
    url: jdbc:h2:mem:nasa_pictures
    username: <USER_NAME>
    password: <PASSWORD>
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
thief:
  nasa-api-key: <API_KEY>